# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ea9c36e6e21735988bdd04f6d6f46885e1d3b0c6928a0876e7ef4c4d08a959098986cf580ceda2955a292c2096d46d4ca830d32842f88319777a8814ba2da09

test:
  secret_key_base: 577e733d3b93cecadb57a04f1eed2a05e25d03a713185eccc8042f1e99b8dbc0064cf2363c9720a6ca631fae92b13bc71afa153b6cc5d091aada8a614e35d4de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
